# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'AutoResizingCollectionView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'FlexLayout'

  # Pods for AutoResizingCollectionView

  target 'AutoResizingCollectionViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AutoResizingCollectionViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
